site_name: Uganda Classifier Predictor

nav:
  - Home: index.md
  - API Reference: api.md

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.instant

plugins:
  - git-revision-date-localized
  - search
  - mkdocstrings

extra:
  url_prefix: !!python/object/apply:os.getenv ["MM_DOCS_URL_PREFIX"]
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/amichuda
      name: My Github
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/aleksandr-michuda-3a839b149/
      name: My Linkedin
    - icon: fontawesome/regular/envelope
      link: mailto:<amichuda@ucdavis.edu>
      name: Email me!
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/econaleks
      name: Follow me on Twitter!

markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - meta
  - admonition
  - attr_list
  - pymdownx.details
  - attr_list
  - footnotes

google_analytics:
  - UA-178740663-2
  - auto

repo_url: https://github.com/amichuda/surname_region_prediction

