site_name: Uganda Classifier Predictor

nav:
  - Home: index.md
  - API Reference: api.md

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.instant

plugins:
  - git-revision-date-localized
  - search
  - mkdocstrings

extra:
  url_prefix: !!python/object/apply:os.getenv ["MM_DOCS_URL_PREFIX"]

markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - meta
  - admonition
  - attr_list
  - pymdownx.details
  - attr_list
  - footnotes